# This workflow allows to check if aws credentials exists in github repositories

name: backup
env:
  variables: 
    repo_source: "https://github.com/lumston/backup_repository"
    repo_target: "targetrepo"

# Controls when the workflow will run
phases:
  check_source:
    - echo "${S3_BUCKET}"
    - git pull ${S3_BUCKET}
