name: scan_credentials_and_backup_repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - '**'
      - '!main'
      - '!qa'
      - '!dev'
  pull_request:
    branches: 
      - 'main'
      - 'qa'
      - 'dev'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#Line to make push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reusable_credentials_workflow:
    uses: lumston/reusable_workflows/.github/workflows/scan_credentials.yml@main
  backup_repo_workflow:
    uses: lumston/backup_repository/.github/workflows/backup.yml@main
    secrets:
      USER_CODECOMMIT: ${{secrets.USER_CODECOMMIT}}
      PASSWORD_CODECOMMIT: ${{secrets.PASSWORD_CODECOMMIT}}
      TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
      AWS_CODECOMMIT_KEY: ${{secrets.AWS_CODECOMMIT_KEY}}
      AWS_CODECOMMIT_SECRET: ${{secrets.AWS_CODECOMMIT_SECRET}}
